services:
  new-filmate:
    volumes:
      - ./.env:/app/.env
      - ./projects:/app/projects
      - ./logs:/app/logs
      - ./vertex_keys:/app/vertex_keys
      - ./cert:/app/cert
      - ./claude_data:/root/.claude
